/*
  Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely.
*/

/* Tests for src/joystick/ble/SDL_ble_zwift_crypto.c, the key exchange of
   older Zwift firmware in hifihedgehog/SDL#33 Part 12, with Zwift replay
   test 14. No public test vectors exist, so test/ble/zwift-crypto-vectors.py
   makes them with the cryptography package, which runs on OpenSSL and shares
   no code with the CNG calls under test. Every input reaches the module as an
   exact-size heap copy and every output lands in an exact-size heap buffer,
   so AddressSanitizer sees a read or write past either. The last blocks run
   the Zwift module's encrypted handshake through the session with this
   module's real crypto. */

#include "testbleharness.h"
#include "SDL_ble_zwift_crypto.h"

/* The curve check and the modular arithmetic behind it run before CNG sees
   a key, and the length and zeroing rules of Decrypt run around its CNG
   call. CNG on this bench rejects the same keys and zeroes the same buffer
   itself, so a broken rule passes every test through the entry points. A
   second copy of the module, compiled into this test under other public
   names, gives the tests at the end its static functions and its keys
   structure. */
SDL_ZwiftKeys *Copy_ZwiftCrypto_Create(SDL_ZwiftCrypto *crypto);
void Copy_ZwiftCrypto_Destroy(SDL_ZwiftKeys *keys);
bool Copy_ZwiftCrypto_SetKeyPair(SDL_ZwiftKeys *keys, const uint8_t *d, const uint8_t *x, const uint8_t *y);
bool Copy_ZwiftCrypto_GetDerived(const SDL_ZwiftKeys *keys, uint8_t *hkdf);

#define SDL_ZwiftCrypto_Create     Copy_ZwiftCrypto_Create
#define SDL_ZwiftCrypto_Destroy    Copy_ZwiftCrypto_Destroy
#define SDL_ZwiftCrypto_SetKeyPair Copy_ZwiftCrypto_SetKeyPair
#define SDL_ZwiftCrypto_GetDerived Copy_ZwiftCrypto_GetDerived
#include "SDL_ble_zwift_crypto.c"
#undef SDL_ZwiftCrypto_Create
#undef SDL_ZwiftCrypto_Destroy
#undef SDL_ZwiftCrypto_SetKeyPair
#undef SDL_ZwiftCrypto_GetDerived

/* Generated by test/ble/zwift-crypto-vectors.py with cryptography 50.0.0. Do not edit. */

/* Zwift test 1: a right half with A pressed */
static const uint8_t message_pressed[19] = {
    0x07, 0x08, 0x00, 0x10, 0x01, 0x18, 0x01, 0x20, 0x00, 0x28, 0x01, 0x30,
    0x01, 0x38, 0x01, 0x40, 0x00, 0x48, 0x00
};

/* The same message with A released */
static const uint8_t message_released[19] = {
    0x07, 0x08, 0x00, 0x10, 0x01, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x30,
    0x01, 0x38, 0x01, 0x40, 0x00, 0x48, 0x00
};

/* The host's private key, SHA-256 of "SDL Zwift test host key" reduced to 1..n-1 */
static const uint8_t host_d[32] = {
    0xCB, 0x45, 0x8C, 0x0E, 0x49, 0xD0, 0xE9, 0xC5, 0xD6, 0x2F, 0x20, 0xB3,
    0xF8, 0x50, 0xF9, 0x34, 0xED, 0xAF, 0xF3, 0xFE, 0x8D, 0xE8, 0xD4, 0xB4,
    0x18, 0xF5, 0xA2, 0x53, 0xC7, 0x52, 0x11, 0x34
};

/* The host's public key, X then Y */
static const uint8_t host_key[64] = {
    0x81, 0x7D, 0x07, 0xD5, 0x67, 0xB2, 0xFA, 0x99, 0x1B, 0x5D, 0x19, 0x8E,
    0xCD, 0x74, 0xF3, 0x0B, 0xAA, 0x4D, 0xC8, 0x8B, 0x94, 0x13, 0x94, 0xFA,
    0xB9, 0x70, 0xE0, 0xD2, 0xDC, 0xF0, 0x30, 0x27, 0xB6, 0x58, 0x9E, 0xF2,
    0x4F, 0xF8, 0x30, 0xA8, 0x29, 0x8F, 0xA3, 0x57, 0x03, 0x42, 0x21, 0x2D,
    0xD2, 0x86, 0x9B, 0xC5, 0x79, 0x79, 0x8A, 0x69, 0x93, 0x42, 0xAC, 0x78,
    0xB7, 0x58, 0xF5, 0xE3
};

/* The device's private key, SHA-256 of "SDL Zwift test device key" reduced to 1..n-1 */
static const uint8_t device_d[32] = {
    0x85, 0xEB, 0x23, 0xAE, 0x39, 0x71, 0x75, 0x8B, 0xB7, 0xB9, 0xDE, 0xCD,
    0x9E, 0xC3, 0x55, 0x87, 0x03, 0xB7, 0x86, 0x55, 0x62, 0xED, 0x9D, 0x34,
    0x4E, 0x09, 0xC1, 0x8B, 0x42, 0x64, 0x2C, 0x48
};

/* The device's public key, X then Y */
static const uint8_t device_key[64] = {
    0x45, 0x7F, 0x87, 0x4D, 0x6C, 0xB5, 0x73, 0xE3, 0x06, 0x44, 0x70, 0x92,
    0x30, 0x9A, 0x91, 0x51, 0xE6, 0x22, 0xC1, 0xB1, 0x0D, 0x7E, 0x81, 0x31,
    0x41, 0x20, 0xC5, 0x1B, 0xC3, 0x09, 0xEA, 0x54, 0xFA, 0x9E, 0xA4, 0x64,
    0x66, 0xB8, 0x5F, 0xBB, 0xFE, 0xE8, 0x8B, 0xC9, 0xBD, 0x00, 0xFC, 0x7B,
    0x16, 0xE9, 0x44, 0xFE, 0x1A, 0xD4, 0x41, 0x05, 0x1C, 0x24, 0x03, 0x37,
    0x22, 0x2D, 0x21, 0xF3
};

/* HKDF output, salted with the device's key then the host's */
static const uint8_t session_hkdf[36] = {
    0x21, 0xD7, 0x81, 0x90, 0x19, 0xE1, 0x5F, 0xF0, 0x9C, 0x93, 0xFA, 0x56,
    0xB0, 0xA0, 0x12, 0x3E, 0xD6, 0xC0, 0x5C, 0x33, 0x4C, 0xF6, 0x9F, 0x07,
    0x81, 0xAC, 0x33, 0xC9, 0x0F, 0x5E, 0x29, 0xCB, 0x3B, 0x04, 0x38, 0x94
};

/* The AES-256 key, HKDF output bytes 0 to 31 */
static const uint8_t session_key[32] = {
    0x21, 0xD7, 0x81, 0x90, 0x19, 0xE1, 0x5F, 0xF0, 0x9C, 0x93, 0xFA, 0x56,
    0xB0, 0xA0, 0x12, 0x3E, 0xD6, 0xC0, 0x5C, 0x33, 0x4C, 0xF6, 0x9F, 0x07,
    0x81, 0xAC, 0x33, 0xC9, 0x0F, 0x5E, 0x29, 0xCB
};

/* The nonce prefix, HKDF output bytes 32 to 35 */
static const uint8_t session_prefix[4] = {
    0x3B, 0x04, 0x38, 0x94
};

/* HKDF output salted the other way round, the device's view */
static const uint8_t mirror_hkdf[36] = {
    0x1F, 0x23, 0x78, 0xF2, 0xC0, 0x54, 0xA6, 0x07, 0x10, 0x08, 0xAB, 0xCD,
    0x3D, 0x0C, 0x00, 0x7F, 0xE5, 0x26, 0xC9, 0x60, 0xC9, 0xCC, 0xB3, 0xD1,
    0xA2, 0x1E, 0x95, 0x4C, 0x62, 0xAB, 0x53, 0x31, 0xD0, 0xC1, 0xA5, 0xC7
};

/* message_pressed under counter 01 00 00 00 */
static const uint8_t frame_pressed[27] = {
    0x01, 0x00, 0x00, 0x00, 0x08, 0xCA, 0x2E, 0x38, 0x82, 0xD0, 0x4E, 0xC5,
    0x1B, 0xBE, 0x7E, 0x37, 0x02, 0x87, 0x3D, 0x11, 0x33, 0xB2, 0x1E, 0x67,
    0x69, 0xC3, 0x0D
};

/* message_released under counter 02 00 00 00 */
static const uint8_t frame_released[27] = {
    0x02, 0x00, 0x00, 0x00, 0x7A, 0x4C, 0x31, 0xE1, 0xEC, 0xD2, 0xC0, 0xE1,
    0xEB, 0x8C, 0x8E, 0xD3, 0xC8, 0xEE, 0x17, 0x57, 0x22, 0xE1, 0x15, 0x37,
    0x9D, 0x97, 0x56
};

/* The first host private key d = 1, 2, 3 and so on whose X starts with 00, d = 379 */
static const uint8_t zero_x_d[32] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x7B
};

/* Its public key, X then Y */
static const uint8_t zero_x_key[64] = {
    0x00, 0x55, 0x43, 0x89, 0x4A, 0xF3, 0xD0, 0x0E, 0xD7, 0xD7, 0x40, 0xAB,
    0xDB, 0xD7, 0x5C, 0x96, 0xB0, 0x68, 0x77, 0xB7, 0x87, 0xDB, 0x5F, 0x70,
    0xEE, 0xA7, 0x8B, 0x90, 0xA8, 0xD7, 0xC0, 0x0A, 0xBB, 0x4C, 0x85, 0xA3,
    0xD8, 0xEA, 0x29, 0xEF, 0xAA, 0xFA, 0x24, 0x40, 0x69, 0x12, 0xDD, 0x84,
    0xD5, 0xB1, 0x4D, 0xC3, 0x2B, 0xF6, 0x56, 0xEF, 0x6C, 0x6B, 0xD5, 0x8A,
    0x5D, 0x94, 0x3F, 0x92
};

/* HKDF output of that host key with the device's key */
static const uint8_t zero_x_hkdf[36] = {
    0xE0, 0x86, 0x99, 0x28, 0x71, 0x22, 0x29, 0x4A, 0xDA, 0x19, 0xD9, 0x8E,
    0x9E, 0xBA, 0x53, 0x10, 0x46, 0xE9, 0xC1, 0xF6, 0x8F, 0x8E, 0xD0, 0x55,
    0x3E, 0x4A, 0x5B, 0xD2, 0xD5, 0x50, 0x9F, 0xB1, 0x4C, 0xDE, 0xF9, 0x3B
};

/* The same salted the other way round */
static const uint8_t zero_x_mirror[36] = {
    0x05, 0xE4, 0x1A, 0xC1, 0x05, 0xE6, 0x77, 0x41, 0xB7, 0x70, 0x38, 0xC0,
    0xD6, 0x77, 0xDA, 0xA5, 0x40, 0x48, 0x1A, 0x7A, 0xBC, 0xD8, 0x1F, 0xEA,
    0x16, 0x68, 0xC3, 0xDF, 0x9A, 0x31, 0xA6, 0x78, 0xFF, 0xC5, 0x52, 0xEB
};

/* message_pressed under counter 01 00 00 00 */
static const uint8_t zero_x_pressed[27] = {
    0x01, 0x00, 0x00, 0x00, 0x9B, 0x47, 0x26, 0x42, 0x28, 0x53, 0xFF, 0xCA,
    0xC5, 0x8D, 0x5C, 0x97, 0xFF, 0x58, 0xD6, 0xDE, 0xCC, 0xC5, 0x2B, 0xDB,
    0x6F, 0xC9, 0x7D
};

/* message_released under counter 02 00 00 00 */
static const uint8_t zero_x_released[27] = {
    0x02, 0x00, 0x00, 0x00, 0xD6, 0xC1, 0x25, 0x82, 0x77, 0xBE, 0x0C, 0x70,
    0xBC, 0x62, 0x7C, 0xC4, 0xA0, 0x63, 0xC6, 0x9D, 0x43, 0x2F, 0xAE, 0xB5,
    0xE6, 0xED, 0xAB
};

/* The first device key d = 1, 2, 3 and so on whose secret with the host's starts with 00, d = 169 */
static const uint8_t zero_secret_key[64] = {
    0xA7, 0xA6, 0xB9, 0x10, 0x23, 0x98, 0xB4, 0xE3, 0x8D, 0xD5, 0xE4, 0x71,
    0x06, 0x2C, 0x97, 0x6F, 0xBC, 0xC5, 0xF9, 0xE5, 0x20, 0xFE, 0xB5, 0xE9,
    0x8A, 0xA7, 0x56, 0x63, 0xB7, 0xA2, 0x31, 0xCA, 0x03, 0x89, 0x21, 0x6E,
    0x45, 0x6E, 0xD7, 0x0C, 0x68, 0x9A, 0xE4, 0x61, 0xFF, 0x48, 0xFF, 0x2F,
    0x65, 0x7A, 0x0D, 0x42, 0xAB, 0x23, 0x30, 0x81, 0x4F, 0xE5, 0x87, 0x52,
    0x0B, 0x20, 0x52, 0x71
};

/* HKDF output of the host's key with that device key */
static const uint8_t zero_secret_hkdf[36] = {
    0x74, 0xF3, 0xF9, 0xAB, 0x15, 0xE3, 0x16, 0xD5, 0x45, 0x43, 0x90, 0x02,
    0x3B, 0x9E, 0xFB, 0x0A, 0xC2, 0x87, 0xB3, 0x62, 0x77, 0x1D, 0x45, 0xE7,
    0xDC, 0xDC, 0xE3, 0x3A, 0x1E, 0x15, 0xCA, 0x1B, 0x90, 0x5B, 0xDD, 0xAE
};

/* The device's key with Y one higher, off the curve */
static const uint8_t off_curve_key[64] = {
    0x45, 0x7F, 0x87, 0x4D, 0x6C, 0xB5, 0x73, 0xE3, 0x06, 0x44, 0x70, 0x92,
    0x30, 0x9A, 0x91, 0x51, 0xE6, 0x22, 0xC1, 0xB1, 0x0D, 0x7E, 0x81, 0x31,
    0x41, 0x20, 0xC5, 0x1B, 0xC3, 0x09, 0xEA, 0x54, 0xFA, 0x9E, 0xA4, 0x64,
    0x66, 0xB8, 0x5F, 0xBB, 0xFE, 0xE8, 0x8B, 0xC9, 0xBD, 0x00, 0xFC, 0x7B,
    0x16, 0xE9, 0x44, 0xFE, 0x1A, 0xD4, 0x41, 0x05, 0x1C, 0x24, 0x03, 0x37,
    0x22, 0x2D, 0x21, 0xF4
};

/* The point with X = 0, on the curve */
static const uint8_t low_x_key[64] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x66, 0x48, 0x5C, 0x78,
    0x0E, 0x2F, 0x83, 0xD7, 0x24, 0x33, 0xBD, 0x5D, 0x84, 0xA0, 0x6B, 0xB6,
    0x54, 0x1C, 0x2A, 0xF3, 0x1D, 0xAE, 0x87, 0x17, 0x28, 0xBF, 0x85, 0x6A,
    0x17, 0x4F, 0x93, 0xF4
};

/* The same point with X = p, out of range */
static const uint8_t wide_x_key[64] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x66, 0x48, 0x5C, 0x78,
    0x0E, 0x2F, 0x83, 0xD7, 0x24, 0x33, 0xBD, 0x5D, 0x84, 0xA0, 0x6B, 0xB6,
    0x54, 0x1C, 0x2A, 0xF3, 0x1D, 0xAE, 0x87, 0x17, 0x28, 0xBF, 0x85, 0x6A,
    0x17, 0x4F, 0x93, 0xF4
};

/* End of generated vectors */

#define KEY_SIZE     SDL_ZWIFT_KEY_SIZE
#define HKDF_SIZE    SDL_ZWIFT_HKDF_SIZE
#define FRAME_SIZE   sizeof(frame_pressed)
#define MESSAGE_SIZE sizeof(message_pressed)
#define EAST_BIT     (1u << SDL_BLE_BUTTON_EAST)

static const uint8_t ride_on[6] = { 0x52, 0x69, 0x64, 0x65, 0x4F, 0x6E };

typedef void (*TestFunction)(void);

/* Runs one block and prints its own check count */
static void Run(const char *label, TestFunction test)
{
    const int checks = bh_checks;
    const int failures = bh_failures;

    test();
    printf("%s: %d checks, %d failures\n", label, bh_checks - checks, bh_failures - failures);
}

static bool Same(const uint8_t *a, const uint8_t *b, size_t length)
{
    return memcmp(a, b, length) == 0;
}

static bool AllZero(const uint8_t *data, size_t length)
{
    size_t i;

    for (i = 0; i < length; ++i) {
        if (data[i] != 0) {
            return false;
        }
    }
    return true;
}

/* An exact-size heap copy. An empty one is malloc(0), a block with no bytes,
   so AddressSanitizer reports a read of its byte 0. It may be NULL. */
static uint8_t *Copy(const uint8_t *data, size_t length)
{
    uint8_t *copy = (uint8_t *)malloc(length);

    if (!copy && length) {
        printf("out of memory\n");
        exit(2);
    }
    if (length) {
        memcpy(copy, data, length);
    }
    return copy;
}

/* A key exchange, or NULL after a failed check when CNG does not load */
static SDL_ZwiftKeys *NewKeys(SDL_ZwiftCrypto *crypto)
{
    SDL_ZwiftKeys *keys = SDL_ZwiftCrypto_Create(crypto);

    BH_CHECK(keys != NULL, "CNG did not load");
    return keys;
}

static bool SetPair(SDL_ZwiftKeys *keys, const uint8_t *d, const uint8_t *key)
{
    return SDL_ZwiftCrypto_SetKeyPair(keys, d, key, &key[32]);
}

/* MakeKey into an exact-size buffer */
static bool MakeKey(const SDL_ZwiftCrypto *crypto, uint8_t *key)
{
    uint8_t *out = (uint8_t *)malloc(KEY_SIZE);
    bool result;

    if (!out) {
        printf("out of memory\n");
        exit(2);
    }
    result = crypto->MakeKey(crypto->userdata, out);
    memcpy(key, out, KEY_SIZE);
    free(out);
    return result;
}

/* Derive from an exact-size copy of the device's key */
static bool Derive(const SDL_ZwiftCrypto *crypto, const uint8_t *key)
{
    uint8_t *copy = Copy(key, KEY_SIZE);
    const bool result = crypto->Derive(crypto->userdata, copy);

    free(copy);
    return result;
}

/* Decrypt from an exact-size copy of the frame into an exact-size buffer.
   out receives length - 8 bytes, or nothing for a frame of 8 bytes or less. */
static bool Decrypt(const SDL_ZwiftCrypto *crypto, const uint8_t *frame, size_t length, uint8_t *out)
{
    const size_t count = (length > SDL_ZWIFT_FRAME_EXTRA) ? length - SDL_ZWIFT_FRAME_EXTRA : 0;
    uint8_t *copy = Copy(frame, length);
    uint8_t *plain = (uint8_t *)malloc(count);
    bool result;

    if (!plain && count) {
        printf("out of memory\n");
        exit(2);
    }
    if (count) {
        memset(plain, 0xA5, count);
    }
    result = crypto->Decrypt(crypto->userdata, copy, length, plain);
    if (count) {
        memcpy(out, plain, count);
    }
    free(plain);
    free(copy);
    return result;
}

static bool Derived(const SDL_ZwiftKeys *keys, const uint8_t *expected)
{
    uint8_t hkdf[HKDF_SIZE];

    return SDL_ZwiftCrypto_GetDerived(keys, hkdf) && Same(hkdf, expected, HKDF_SIZE);
}

/* Create fills the entry points, and nothing works before its step */
static void TestEntryPoints(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys;
    uint8_t hkdf[HKDF_SIZE], plain[FRAME_SIZE];

    BH_CHECK(SDL_ZwiftCrypto_Create(NULL) == NULL, "Create without entry points");
    SDL_ZwiftCrypto_Destroy(NULL);
    BH_CHECK(!SDL_ZwiftCrypto_GetDerived(NULL, hkdf), "GetDerived without keys");
    BH_CHECK(!SDL_ZwiftCrypto_SetKeyPair(NULL, host_d, host_key, &host_key[32]), "SetKeyPair without keys");

    memset(&crypto, 0xCC, sizeof(crypto));
    keys = NewKeys(&crypto);
    if (!keys) {
        return;
    }
    BH_CHECK(crypto.userdata == keys && crypto.MakeKey && crypto.Derive && crypto.Decrypt, "entry points");
    BH_CHECK(!SDL_ZwiftCrypto_GetDerived(keys, hkdf), "derived before any Derive");
    BH_CHECK(!Derive(&crypto, device_key), "Derive before a key pair");
    BH_CHECK(!Decrypt(&crypto, frame_pressed, FRAME_SIZE, plain), "Decrypt before Derive");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* Test 14: with fixed private keys for both sides, the HKDF output, key and
   nonce prefix equal the independent values, and the frame that side
   encrypted under counter 01 00 00 00 decrypts to the message of test 1 */
static void Test14_Vectors(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    uint8_t key[KEY_SIZE], hkdf[HKDF_SIZE], plain[FRAME_SIZE];

    if (!keys) {
        return;
    }
    BH_CHECK(SetPair(keys, host_d, host_key), "SetKeyPair");
    BH_CHECK(MakeKey(&crypto, key) && Same(key, host_key, KEY_SIZE), "the fixed key is the one sent");
    BH_CHECK(!SDL_ZwiftCrypto_GetDerived(keys, hkdf), "derived before Derive");
    BH_CHECK(Derive(&crypto, device_key), "Derive");
    BH_CHECK(SDL_ZwiftCrypto_GetDerived(keys, hkdf), "GetDerived");
    BH_CHECK(Same(hkdf, session_hkdf, HKDF_SIZE), "HKDF output");
    BH_CHECK(Same(hkdf, session_key, sizeof(session_key)), "AES key, bytes 0 to 31");
    BH_CHECK(Same(&hkdf[32], session_prefix, sizeof(session_prefix)), "nonce prefix, bytes 32 to 35");
    BH_CHECK(Decrypt(&crypto, frame_pressed, FRAME_SIZE, plain), "counter 01 00 00 00 decrypts");
    BH_CHECK(Same(plain, message_pressed, MESSAGE_SIZE), "to the message of test 1");
    BH_CHECK(Decrypt(&crypto, frame_released, FRAME_SIZE, plain), "counter 02 00 00 00 decrypts");
    BH_CHECK(Same(plain, message_released, MESSAGE_SIZE), "to the released message");
    /* The same exchange again gives the same session */
    BH_CHECK(Derive(&crypto, device_key) && Derived(keys, session_hkdf), "a second Derive");
    BH_CHECK(Decrypt(&crypto, frame_pressed, FRAME_SIZE, plain) && Same(plain, message_pressed, MESSAGE_SIZE),
             "decrypts after a second Derive");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* Test 14: a flipped tag bit drops the frame. So do a flipped ciphertext bit,
   another counter, a truncated frame and a longer one, and every dropped
   frame leaves plain zeroed. */
static void Test14_Tampering(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    uint8_t frame[FRAME_SIZE + 1], plain[FRAME_SIZE];
    size_t length, i;
    int bit;

    if (!keys) {
        return;
    }
    BH_CHECK(SetPair(keys, host_d, host_key) && Derive(&crypto, device_key), "exchange");

    /* Every bit of the tag */
    for (i = FRAME_SIZE - 4; i < FRAME_SIZE; ++i) {
        for (bit = 0; bit < 8; ++bit) {
            memcpy(frame, frame_pressed, FRAME_SIZE);
            frame[i] ^= (uint8_t)(1u << bit);
            BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE, plain), "tag byte %d bit %d flipped", (int)i, bit);
            BH_CHECK(AllZero(plain, MESSAGE_SIZE), "tag byte %d bit %d left plain bytes", (int)i, bit);
        }
    }
    /* Every bit of the ciphertext */
    for (i = 4; i < FRAME_SIZE - 4; ++i) {
        for (bit = 0; bit < 8; ++bit) {
            memcpy(frame, frame_pressed, FRAME_SIZE);
            frame[i] ^= (uint8_t)(1u << bit);
            BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE, plain), "ciphertext byte %d bit %d flipped", (int)i, bit);
        }
    }
    /* Every bit of the counter: the nonce takes its bytes as received */
    for (i = 0; i < 4; ++i) {
        for (bit = 0; bit < 8; ++bit) {
            memcpy(frame, frame_pressed, FRAME_SIZE);
            frame[i] ^= (uint8_t)(1u << bit);
            BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE, plain), "counter byte %d bit %d flipped", (int)i, bit);
        }
    }
    /* The counter as a big-endian number */
    memcpy(frame, frame_pressed, FRAME_SIZE);
    frame[0] = 0x00;
    frame[3] = 0x01;
    BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE, plain), "counter 00 00 00 01");
    /* The released frame's ciphertext under the pressed frame's counter */
    memcpy(frame, frame_released, FRAME_SIZE);
    memcpy(frame, frame_pressed, 4);
    BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE, plain), "a ciphertext under another counter");
    /* Every truncation */
    for (length = 0; length < FRAME_SIZE; ++length) {
        BH_CHECK(!Decrypt(&crypto, frame_pressed, length, plain), "truncated to %d bytes", (int)length);
    }
    /* A byte more */
    memcpy(frame, frame_pressed, FRAME_SIZE);
    frame[FRAME_SIZE] = 0x00;
    BH_CHECK(!Decrypt(&crypto, frame, FRAME_SIZE + 1, plain), "a byte more");
    /* Positive control after every dropped frame */
    BH_CHECK(Decrypt(&crypto, frame_pressed, FRAME_SIZE, plain) && Same(plain, message_pressed, MESSAGE_SIZE),
             "the untouched frame");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* Test 14: a key with a zero first byte in X is sent as 64 bytes, salts HKDF
   whole and decrypts that exchange's frames */
static void Test14_ZeroX(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    uint8_t key[KEY_SIZE], plain[FRAME_SIZE];

    if (!keys) {
        return;
    }
    BH_CHECK(zero_x_key[0] == 0x00, "the vector's X starts with 00");
    BH_CHECK(SetPair(keys, zero_x_d, zero_x_key), "SetKeyPair");
    memset(key, 0xA5, sizeof(key));
    BH_CHECK(MakeKey(&crypto, key), "MakeKey");
    BH_CHECK(key[0] == 0x00 && Same(key, zero_x_key, KEY_SIZE), "all 64 bytes, the leading 00 kept");
    BH_CHECK(Derive(&crypto, device_key) && Derived(keys, zero_x_hkdf), "HKDF with the whole key in the salt");
    BH_CHECK(Decrypt(&crypto, zero_x_pressed, FRAME_SIZE, plain) && Same(plain, message_pressed, MESSAGE_SIZE),
             "that exchange's frame");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* A shared secret whose first byte is 00 is used whole */
static void TestZeroSecret(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);

    if (!keys) {
        return;
    }
    BH_CHECK(SetPair(keys, host_d, host_key), "SetKeyPair");
    BH_CHECK(Derive(&crypto, zero_secret_key), "Derive");
    BH_CHECK(Derived(keys, zero_secret_hkdf), "HKDF over all 32 bytes of the secret");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* Derive takes only a point on the curve with coordinates below p. A
   rejected key leaves no session. */
static void TestDeviceKeys(void)
{
    static const uint8_t zeros[KEY_SIZE] = { 0 };
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    uint8_t hkdf[HKDF_SIZE], plain[FRAME_SIZE];

    if (!keys) {
        return;
    }
    BH_CHECK(SetPair(keys, host_d, host_key), "SetKeyPair");
    BH_CHECK(Derive(&crypto, device_key), "positive control");
    BH_CHECK(!Derive(&crypto, off_curve_key), "a point off the curve");
    BH_CHECK(!SDL_ZwiftCrypto_GetDerived(keys, hkdf), "a rejected key left a session");
    BH_CHECK(!Decrypt(&crypto, frame_pressed, FRAME_SIZE, plain), "a rejected key left a key to decrypt with");
    BH_CHECK(!Derive(&crypto, wide_x_key), "X equal to p");
    /* b is not 0, so (0, 0) is off the curve */
    BH_CHECK(!Derive(&crypto, zeros), "all zeros");
    /* Edge points on the curve are taken */
    BH_CHECK(Derive(&crypto, low_x_key), "the point with X = 0");
    BH_CHECK(Derive(&crypto, zero_x_key), "a point whose X starts with 00");
    BH_CHECK(Derive(&crypto, host_key), "the host's own key");
    BH_CHECK(Derive(&crypto, device_key) && Derived(keys, session_hkdf), "the device's key after the rejections");
    SDL_ZwiftCrypto_Destroy(keys);
}

/* MakeKey gives a new key each time, a point on the curve that a device can
   derive from, and a new exchange drops the old session */
static void TestMakeKey(void)
{
    SDL_ZwiftCrypto crypto, other_crypto, device_crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    SDL_ZwiftKeys *other = NewKeys(&other_crypto);
    SDL_ZwiftKeys *device = NewKeys(&device_crypto);
    uint8_t first[KEY_SIZE], second[KEY_SIZE], third[KEY_SIZE], hkdf[HKDF_SIZE];

    if (keys && other && device) {
        BH_CHECK(SetPair(device, device_d, device_key), "the device's pair");
        BH_CHECK(MakeKey(&crypto, first), "first MakeKey");
        BH_CHECK(MakeKey(&crypto, second), "second MakeKey");
        BH_CHECK(MakeKey(&other_crypto, third), "another exchange's MakeKey");
        BH_CHECK(!Same(first, second, KEY_SIZE) && !Same(first, third, KEY_SIZE) && !Same(second, third, KEY_SIZE),
                 "every key is new");
        BH_CHECK(Derive(&device_crypto, first) && Derive(&device_crypto, second) && Derive(&device_crypto, third),
                 "every key is a point on the curve");
        BH_CHECK(Derive(&crypto, device_key) && SDL_ZwiftCrypto_GetDerived(keys, hkdf), "the host derives");
        BH_CHECK(!Same(hkdf, session_hkdf, HKDF_SIZE), "with its own key, not the fixed one");
        BH_CHECK(MakeKey(&crypto, first), "a new exchange");
        BH_CHECK(!SDL_ZwiftCrypto_GetDerived(keys, hkdf), "the old session went with it");
        BH_CHECK(!Same(first, second, KEY_SIZE), "a new key again");
        /* A fixed pair stays in place, and a new exchange on it still drops
           the old session */
        BH_CHECK(SetPair(keys, host_d, host_key), "SetKeyPair");
        BH_CHECK(MakeKey(&crypto, first) && Same(first, host_key, KEY_SIZE), "the fixed key");
        BH_CHECK(Derive(&crypto, device_key) && Derived(keys, session_hkdf), "the fixed pair derives");
        BH_CHECK(MakeKey(&crypto, second) && Same(second, host_key, KEY_SIZE), "the fixed key again");
        BH_CHECK(!SDL_ZwiftCrypto_GetDerived(keys, hkdf), "the fixed pair's old session went with it");
    }
    SDL_ZwiftCrypto_Destroy(keys);
    SDL_ZwiftCrypto_Destroy(other);
    SDL_ZwiftCrypto_Destroy(device);
}

/* The index of the last write in the log, -1 when none */
static int LastWrite(const BH_Harness *h)
{
    int i;

    for (i = h->nactions - 1; i >= 0; --i) {
        if (h->actions[i].action.kind == SDL_BLE_ACTION_WRITE) {
            return i;
        }
    }
    return -1;
}

/* A right half of firmware 1.x on the session, run until the key exchange
   is written. NULL when the handshake did not go as the part says. */
static BH_Harness *KeySent(const SDL_ZwiftCrypto *crypto, const uint8_t *key)
{
    BH_Harness *h = BH_Create(&SDL_BLEZwiftFamily, SDL_ZWIFT_PLAY_RIGHT, crypto, false);
    const SDL_BLEAction *action;
    int writes[4];
    int index;

    BH_Start(h, false);
    BH_CHECK(BH_Writes(h, writes, 4) == 1 && BH_IsWrite(h, writes[0], ride_on, sizeof(ride_on)), "RideOn first");
    BH_WriteAll(h);
    /* No ASYNC value within 10 s of the write */
    BH_Advance(h, h->now + SDL_ZWIFT_HANDSHAKE_MS);
    BH_CHECK(BH_Writes(h, writes, 4) == 2, "one more write after 10 s");
    index = LastWrite(h);
    if (index < 0) {
        BH_Destroy(h);
        return NULL;
    }
    action = &h->actions[index].action;
    BH_CHECK(action->characteristic == SDL_ZWIFT_SYNC_RX && action->response, "to SYNC_RX with a response");
    BH_CHECK(action->length == 8 + KEY_SIZE, "RideOn, two bytes and 64 key bytes, %d bytes written", action->length);
    BH_CHECK(Same(action->data, ride_on, sizeof(ride_on)) && action->data[6] == 0x01 && action->data[7] == 0x02,
             "RideOn 01 02");
    BH_CHECK(Same(&action->data[8], key, KEY_SIZE), "the host's key, all 64 bytes");
    if (action->length != 8 + KEY_SIZE) {
        BH_Destroy(h);
        return NULL;
    }
    return h;
}

/* The Zwift module's encrypted handshake end to end: the host's key on the
   wire, the device's answer on SYNC_TX, then encrypted ASYNC frames */
static void Session(const uint8_t *d, const uint8_t *key, const uint8_t *hkdf, const uint8_t *mirror,
                    const uint8_t *pressed, const uint8_t *released)
{
    SDL_ZwiftCrypto crypto, device_crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    SDL_ZwiftKeys *device = NewKeys(&device_crypto);
    BH_Harness *h = NULL;
    uint8_t reply[8 + KEY_SIZE], wire[KEY_SIZE], plain[FRAME_SIZE], frame[FRAME_SIZE];
    int snapshots;

    if (keys && device) {
        BH_CHECK(SetPair(keys, d, key), "the host's pair");
        BH_CHECK(SetPair(device, device_d, device_key), "the device's pair");
        h = KeySent(&crypto, key);
    }
    if (h) {
        /* The device's side of the exchange, from the key on the wire. Its
           own SDL_ZwiftKeys salts with its peer's key first. */
        memcpy(wire, &h->actions[LastWrite(h)].action.data[8], KEY_SIZE);
        BH_CHECK(Derive(&device_crypto, wire) && Derived(device, mirror), "the device's view of the secret");

        /* RideOn, two bytes and the device's key, 01 01 as in zwiftplay's capture */
        memcpy(reply, ride_on, sizeof(ride_on));
        reply[6] = 0x01;
        reply[7] = 0x01;
        BH_CHECK(MakeKey(&device_crypto, &reply[8]) && Same(&reply[8], device_key, KEY_SIZE), "the device's key");
        BH_Value(h, SDL_ZWIFT_SYNC_TX, reply, sizeof(reply), false);
        BH_CHECK(Derived(keys, hkdf), "the host derived the independent HKDF output");
        BH_CHECK(!h->published && h->nsnapshots == 0, "nothing published before the first frame");

        /* An encrypted frame from the independent side: A pressed */
        BH_Value(h, SDL_ZWIFT_ASYNC, pressed, FRAME_SIZE, false);
        BH_CHECK(h->published && BH_Count(h, SDL_BLE_ACTION_PUBLISH) == 1, "the session published");
        BH_CHECK(BH_Controls(h)->buttons == EAST_BIT, "EAST only, buttons %08x", (unsigned)BH_Controls(h)->buttons);
        BH_CHECK(BH_Axis(h, SDL_BLE_AXIS_RIGHTX) == 0 && BH_Axis(h, SDL_BLE_AXIS_RIGHT_TRIGGER) == -32768,
                 "RIGHTX 0 and RIGHT_TRIGGER at rest");

        /* A flipped tag bit changes nothing */
        snapshots = h->nsnapshots;
        memcpy(frame, released, FRAME_SIZE);
        frame[FRAME_SIZE - 1] ^= 0x01;
        BH_Value(h, SDL_ZWIFT_ASYNC, frame, FRAME_SIZE, false);
        BH_CHECK(h->nsnapshots == snapshots && BH_Button(h, SDL_BLE_BUTTON_EAST), "a tampered frame was applied");
        /* A plain message after the exchange is not a frame */
        BH_Value(h, SDL_ZWIFT_ASYNC, message_released, MESSAGE_SIZE, false);
        BH_CHECK(h->nsnapshots == snapshots && BH_Button(h, SDL_BLE_BUTTON_EAST), "a plain message was applied");

        /* The next counter releases A */
        BH_Value(h, SDL_ZWIFT_ASYNC, released, FRAME_SIZE, false);
        BH_CHECK(h->nsnapshots == snapshots + 1 && BH_Controls(h)->buttons == 0, "EAST released");
        BH_CHECK(!SDL_BLESession_Ended(&h->session) && BH_Count(h, SDL_BLE_ACTION_BACKOFF) == 0, "the session runs");

        /* The host's decrypt matches the independent side for both frames */
        BH_CHECK(Decrypt(&crypto, pressed, FRAME_SIZE, plain) && Same(plain, message_pressed, MESSAGE_SIZE),
                 "the pressed frame");
        BH_Destroy(h);
    }
    SDL_ZwiftCrypto_Destroy(keys);
    SDL_ZwiftCrypto_Destroy(device);
}

static void TestSession(void)
{
    Session(host_d, host_key, session_hkdf, mirror_hkdf, frame_pressed, frame_released);
}

/* Test 14 on the wire: the key whose X starts with 00 goes out as 64 bytes */
static void TestSessionZeroX(void)
{
    Session(zero_x_d, zero_x_key, zero_x_hkdf, zero_x_mirror, zero_x_pressed, zero_x_released);
}

/* A device key off the curve ends the session with a backoff and publishes
   nothing */
static void TestSessionBadKey(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = NewKeys(&crypto);
    BH_Harness *h = NULL;
    uint8_t reply[8 + KEY_SIZE];

    if (keys) {
        BH_CHECK(SetPair(keys, host_d, host_key), "the host's pair");
        h = KeySent(&crypto, host_key);
    }
    if (h) {
        memcpy(reply, ride_on, sizeof(ride_on));
        reply[6] = 0x01;
        reply[7] = 0x01;
        memcpy(&reply[8], off_curve_key, KEY_SIZE);
        BH_Value(h, SDL_ZWIFT_SYNC_TX, reply, sizeof(reply), false);
        BH_CHECK(SDL_BLESession_Ended(&h->session), "the session ended");
        BH_CHECK(BH_Count(h, SDL_BLE_ACTION_BACKOFF) == 1 && BH_Count(h, SDL_BLE_ACTION_DISCONNECT) == 1,
                 "with a backoff and a disconnect");
        BH_CHECK(BH_Count(h, SDL_BLE_ACTION_PUBLISH) == 0 && !h->published, "nothing published");
        BH_Value(h, SDL_ZWIFT_ASYNC, frame_pressed, FRAME_SIZE, false);
        BH_CHECK(h->nsnapshots == 0 && BH_Controls(h)->buttons == 0, "a frame after the end was applied");
        BH_Destroy(h);
    }
    SDL_ZwiftCrypto_Destroy(keys);
}

/* The P-256 generator of SEC 2 v2, 2.4.2 "Recommended Parameters
   secp256r1", and its negation, y = p - Gy */
static const uint8_t curve_gx[32] = {
    0x6B, 0x17, 0xD1, 0xF2, 0xE1, 0x2C, 0x42, 0x47, 0xF8, 0xBC, 0xE6, 0xE5, 0x63, 0xA4, 0x40, 0xF2,
    0x77, 0x03, 0x7D, 0x81, 0x2D, 0xEB, 0x33, 0xA0, 0xF4, 0xA1, 0x39, 0x45, 0xD8, 0x98, 0xC2, 0x96
};
static const uint8_t curve_gy[32] = {
    0x4F, 0xE3, 0x42, 0xE2, 0xFE, 0x1A, 0x7F, 0x9B, 0x8E, 0xE7, 0xEB, 0x4A, 0x7C, 0x0F, 0x9E, 0x16,
    0x2B, 0xCE, 0x33, 0x57, 0x6B, 0x31, 0x5E, 0xCE, 0xCB, 0xB6, 0x40, 0x68, 0x37, 0xBF, 0x51, 0xF5
};
static const uint8_t curve_gy_negated[32] = {
    0xB0, 0x1C, 0xBD, 0x1C, 0x01, 0xE5, 0x80, 0x65, 0x71, 0x18, 0x14, 0xB5, 0x83, 0xF0, 0x61, 0xE9,
    0xD4, 0x31, 0xCC, 0xA9, 0x94, 0xCE, 0xA1, 0x31, 0x34, 0x49, 0xBF, 0x97, 0xC8, 0x40, 0xAE, 0x0A
};

/* The point whose y is 1. Its x solves x^3 - 3x + b = 1 modulo p, found by
   splitting that cubic over GF(p) with Python integers and checked against
   the curve equation there. y + p still fits in 32 bytes. */
static const uint8_t curve_x1[32] = {
    0x09, 0xE7, 0x8D, 0x4E, 0xF6, 0x0D, 0x05, 0xF7, 0x50, 0xF6, 0x63, 0x62, 0x09, 0x09, 0x2B, 0xC4,
    0x3C, 0xBD, 0xD6, 0xB4, 0x7E, 0x11, 0xA9, 0xDE, 0x20, 0xA9, 0xFE, 0xB2, 0xA5, 0x0B, 0xB9, 0x6C
};
static const uint8_t curve_one[32] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01
};

/* p - 2, p - 1 and p + 1 */
static const uint8_t curve_p_minus_2[32] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFD
};
static const uint8_t curve_p_minus_1[32] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE
};
static const uint8_t curve_p_plus_1[32] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* A key of x then y */
static void Point(uint8_t *point, const uint8_t *x, const uint8_t *y)
{
    memcpy(point, x, 32);
    memcpy(&point[32], y, 32);
}

/* The copy's ZwiftCrypto_OnCurve on points on and off the curve, with each
   coordinate on both sides of p */
static void TestCurveCheck(void)
{
    static const uint8_t zeros[32] = { 0 };
    uint8_t point[KEY_SIZE];

    Point(point, curve_gx, curve_gy);
    BH_CHECK(ZwiftCrypto_OnCurve(point), "the generator is on the curve");
    Point(point, curve_gx, curve_gy_negated);
    BH_CHECK(ZwiftCrypto_OnCurve(point), "the generator negated is on the curve");
    BH_CHECK(ZwiftCrypto_OnCurve(device_key) && ZwiftCrypto_OnCurve(host_key) && ZwiftCrypto_OnCurve(zero_x_key) &&
                 ZwiftCrypto_OnCurve(zero_secret_key) && ZwiftCrypto_OnCurve(low_x_key),
             "the vectors' keys and the point with x = 0 are on the curve");
    Point(point, curve_x1, curve_one);
    BH_CHECK(ZwiftCrypto_OnCurve(point), "the point with y = 1 is on the curve");

    BH_CHECK(!ZwiftCrypto_OnCurve(off_curve_key), "the device's key with y one higher is off the curve");
    Point(point, zeros, zeros);
    BH_CHECK(!ZwiftCrypto_OnCurve(point), "(0, 0) is off the curve");
    /* x = p is 0 modulo p and y = p + 1 is 1 modulo p, so both points
       satisfy the equation modulo p: only the range check turns them down */
    BH_CHECK(!ZwiftCrypto_OnCurve(wide_x_key), "x = p is out of range");
    Point(point, curve_x1, curve_p_plus_1);
    BH_CHECK(!ZwiftCrypto_OnCurve(point), "y = p + 1 is out of range");
    Point(point, curve_x1, zwift_p256_p);
    BH_CHECK(!ZwiftCrypto_OnCurve(point), "y = p is out of range");
    memset(point, 0xFF, sizeof(point));
    BH_CHECK(!ZwiftCrypto_OnCurve(point), "every byte FF is out of range");
}

/* The arithmetic behind the check: which of two numbers is larger, a sum of
   exactly p, a sum past 2^256 and a product */
static void TestCurveArithmetic(void)
{
    uint32_t prime[ZWIFT_LIMBS], below[ZWIFT_LIMBS], above[ZWIFT_LIMBS], wanted[ZWIFT_LIMBS];
    uint32_t sum[ZWIFT_LIMBS], zero[ZWIFT_LIMBS], unit[ZWIFT_LIMBS];

    ZwiftCrypto_Limbs(prime, zwift_p256_p);
    ZwiftCrypto_Limbs(below, curve_p_minus_1);
    ZwiftCrypto_Limbs(above, curve_p_plus_1);
    memset(zero, 0, sizeof(zero));
    memset(unit, 0, sizeof(unit));
    unit[0] = 1;

    /* p + 1 and p differ in their four lowest limbs. The fourth decides,
       although p's lowest limb is the larger. */
    BH_CHECK(ZwiftCrypto_Compare(above, prime) == 1 && ZwiftCrypto_Compare(prime, above) == -1, "p + 1 is above p");
    BH_CHECK(ZwiftCrypto_Compare(below, prime) == -1 && ZwiftCrypto_Compare(prime, prime) == 0, "p - 1 is below p");
    /* 1 + (p - 1) is p, which reduces to 0 */
    ZwiftCrypto_AddMod(sum, unit, below, prime);
    BH_CHECK(memcmp(sum, zero, sizeof(sum)) == 0, "1 + (p - 1) is 0");
    /* (p - 1) + (p - 1) carries past 2^256 and reduces to p - 2 */
    ZwiftCrypto_AddMod(sum, below, below, prime);
    ZwiftCrypto_Limbs(wanted, curve_p_minus_2);
    BH_CHECK(memcmp(sum, wanted, sizeof(sum)) == 0, "(p - 1) + (p - 1) is p - 2");
    /* (p - 1) x (p - 1) is 1 */
    ZwiftCrypto_MulMod(sum, below, below, prime);
    BH_CHECK(memcmp(sum, unit, sizeof(sum)) == 0, "(p - 1) x (p - 1) is 1");
}

static ZwiftCrypto_ImportKeyPairFunc real_import;
static int imports;

/* Counts the calls of BCryptImportKeyPair and passes each on */
static NTSTATUS WINAPI CountingImport(BCRYPT_ALG_HANDLE algorithm, BCRYPT_KEY_HANDLE import_key, LPCWSTR blob_type,
                                      BCRYPT_KEY_HANDLE *imported, PUCHAR input, ULONG input_size, ULONG flags)
{
    ++imports;
    return real_import(algorithm, import_key, blob_type, imported, input, input_size, flags);
}

/* Derive checks the device's key before CNG sees it */
static void TestCheckedFirst(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = Copy_ZwiftCrypto_Create(&crypto);
    uint8_t derived[HKDF_SIZE];

    BH_CHECK(keys != NULL, "the copy did not load CNG");
    if (!keys) {
        return;
    }
    BH_CHECK(Copy_ZwiftCrypto_SetKeyPair(keys, host_d, host_key, &host_key[32]), "the copy's pair");
    real_import = keys->ImportKeyPair;
    keys->ImportKeyPair = CountingImport;
    imports = 0;
    BH_CHECK(!Derive(&crypto, off_curve_key) && imports == 0, "a key off the curve reached CNG");
    BH_CHECK(!Derive(&crypto, wide_x_key) && imports == 0, "x = p reached CNG");
    BH_CHECK(Derive(&crypto, device_key) && imports == 1 && Copy_ZwiftCrypto_GetDerived(keys, derived) &&
                 Same(derived, session_hkdf, HKDF_SIZE),
             "the device's key reaches CNG once and derives the vectors' output");
    keys->ImportKeyPair = real_import;
    Copy_ZwiftCrypto_Destroy(keys);
}

static int fake_decrypts;
static NTSTATUS fake_decrypt_status;
static ULONG fake_decrypt_short;

/* Stands in for BCryptDecrypt: fills the output with 5A, reports all of it
   but fake_decrypt_short bytes and returns fake_decrypt_status */
static NTSTATUS WINAPI FakeDecrypt(BCRYPT_KEY_HANDLE cipher, PUCHAR input, ULONG input_size, VOID *padding, PUCHAR iv,
                                   ULONG iv_size, PUCHAR output, ULONG output_size, ULONG *written, ULONG flags)
{
    (void)cipher;
    (void)input;
    (void)input_size;
    (void)padding;
    (void)iv;
    (void)iv_size;
    (void)flags;
    ++fake_decrypts;
    memset(output, 0x5A, output_size);
    *written = output_size - fake_decrypt_short;
    return fake_decrypt_status;
}

/* Decrypt hands CNG frames of 9 to 512 bytes only, and a frame CNG turns
   down, or opens short, leaves plain zeroed, whatever CNG wrote into it */
static void TestDecryptRules(void)
{
    static const size_t lengths[] = { 8, 9, 512, 513 };
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = Copy_ZwiftCrypto_Create(&crypto);
    ZwiftCrypto_DecryptFunc real_decrypt;
    uint8_t *frame, *plain, message[FRAME_SIZE];
    size_t i;

    BH_CHECK(keys != NULL, "the copy did not load CNG");
    if (!keys) {
        return;
    }
    BH_CHECK(Copy_ZwiftCrypto_SetKeyPair(keys, host_d, host_key, &host_key[32]) && Derive(&crypto, device_key),
             "the copy's session");
    real_decrypt = keys->Decrypt;
    keys->Decrypt = FakeDecrypt;
    fake_decrypt_status = 0;
    for (i = 0; i < sizeof(lengths) / sizeof(lengths[0]); ++i) {
        const size_t length = lengths[i];
        const size_t count = (length > SDL_ZWIFT_FRAME_EXTRA) ? length - SDL_ZWIFT_FRAME_EXTRA : 0;
        const bool opens = length > SDL_ZWIFT_FRAME_EXTRA && length <= 512;
        bool opened;

        frame = (uint8_t *)calloc(1, length);
        plain = (uint8_t *)calloc(1, count);
        if (!frame || (!plain && count)) {
            printf("out of memory\n");
            exit(2);
        }
        fake_decrypts = 0;
        opened = crypto.Decrypt(crypto.userdata, frame, length, plain);
        BH_CHECK(opened == opens && fake_decrypts == (opens ? 1 : 0), "a frame of %d bytes: %s, %d calls of CNG",
                 (int)length, opened ? "opened" : "dropped", fake_decrypts);
        free(frame);
        free(plain);
    }

    frame = Copy(frame_pressed, FRAME_SIZE);
    plain = (uint8_t *)malloc(MESSAGE_SIZE);
    if (!plain) {
        printf("out of memory\n");
        exit(2);
    }
    memset(plain, 0xA5, MESSAGE_SIZE);
    fake_decrypts = 0;
    fake_decrypt_status = (NTSTATUS)0xC000A002L; /* STATUS_AUTH_TAG_MISMATCH */
    BH_CHECK(!crypto.Decrypt(crypto.userdata, frame, FRAME_SIZE, plain) && fake_decrypts == 1 &&
                 AllZero(plain, MESSAGE_SIZE),
             "a frame CNG turns down leaves plain zeroed");
    /* A success that reports a byte less than the ciphertext is turned down
       the same way */
    memset(plain, 0xA5, MESSAGE_SIZE);
    fake_decrypts = 0;
    fake_decrypt_status = 0;
    fake_decrypt_short = 1;
    BH_CHECK(!crypto.Decrypt(crypto.userdata, frame, FRAME_SIZE, plain) && fake_decrypts == 1 &&
                 AllZero(plain, MESSAGE_SIZE),
             "a frame CNG opens a byte short leaves plain zeroed");
    fake_decrypt_short = 0;
    free(frame);
    free(plain);

    /* Positive control: the copy's session opens the vectors' frame with CNG */
    keys->Decrypt = real_decrypt;
    BH_CHECK(Decrypt(&crypto, frame_pressed, FRAME_SIZE, message) && Same(message, message_pressed, MESSAGE_SIZE),
             "the copy decrypts the vectors' frame");
    Copy_ZwiftCrypto_Destroy(keys);
}

/* A new key pair keeps its public key as sent, the host's half of the salt */
static void TestKeptKey(void)
{
    SDL_ZwiftCrypto crypto;
    SDL_ZwiftKeys *keys = Copy_ZwiftCrypto_Create(&crypto);
    uint8_t made[KEY_SIZE];

    BH_CHECK(keys != NULL, "the copy did not load CNG");
    if (!keys) {
        return;
    }
    BH_CHECK(MakeKey(&crypto, made) && keys->pair && !keys->fixed && Same(keys->public_key, made, KEY_SIZE),
             "a new pair keeps the key it sent");
    Copy_ZwiftCrypto_Destroy(keys);
}

int main(void)
{
    Run("Entry points", TestEntryPoints);
    Run("Test 14: fixed keys against the independent vectors", Test14_Vectors);
    Run("Test 14: flipped tag and other tampering", Test14_Tampering);
    Run("Test 14: key whose X starts with 00", Test14_ZeroX);
    Run("Secret whose first byte is 00", TestZeroSecret);
    Run("Device keys on and off the curve", TestDeviceKeys);
    Run("MakeKey", TestMakeKey);
    Run("Session: encrypted handshake end to end", TestSession);
    Run("Session: key whose X starts with 00", TestSessionZeroX);
    Run("Session: device key off the curve", TestSessionBadKey);
    Run("Curve check: points on and off the curve", TestCurveCheck);
    Run("Curve check: the arithmetic behind it", TestCurveArithmetic);
    Run("Curve check: before CNG sees the key", TestCheckedFirst);
    Run("Decrypt: lengths and zeroing around CNG", TestDecryptRules);
    Run("MakeKey: the key kept as sent", TestKeptKey);
    return BH_Report("testblezwiftcrypto");
}
