/*
  A port of the sensor fusion of OpenHMD, src/fusion.c and the parts of
  src/omath.c it uses, at commit 85075b0, for the Oculus Rift DK1 driver of
  the SDL fork. C99, no SDL runtime and no I/O. The magnetometer queue and the
  angular velocity queue, which the fusion stores but never reads, are left
  out.

  Copyright 2013, Fredrik Hultin.
  Copyright 2013, Jakob Bornecrantz.
  SPDX-License-Identifier: BSL-1.0

  Boost Software License - Version 1.0 - August 17th, 2003

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#ifndef SDL_hidapi_riftdk1_fusion_h_
#define SDL_hidapi_riftdk1_fusion_h_

#define SDL_RIFTDK1_FUSION_QUEUE 20

typedef struct SDL_RiftDK1Fusion
{
    float orient[4];                              /* Quaternion x, y, z, w */
    float accel_queue[SDL_RIFTDK1_FUSION_QUEUE][3]; /* World-frame acceleration, the last 20 */
    int accel_at;
    int iterations;
    float time;
    int device_level_count;
    float grav_error_angle;
    float grav_error_axis[3];
    float grav_gain;
    int use_gravity; /* OpenHMD's FF_USE_GRAVITY, on by default */
} SDL_RiftDK1Fusion;

/* The identity orientation and gravity correction on */
extern void SDL_RiftDK1_FusionInit(SDL_RiftDK1Fusion *fusion);

/* One sample: dt in seconds, angular velocity in rad/s, acceleration in m/s^2,
 * both in the HMD frame, X right, Y up, Z back */
extern void SDL_RiftDK1_FusionUpdate(SDL_RiftDK1Fusion *fusion, float dt, const float ang_vel[3], const float accel[3]);

#endif /* SDL_hidapi_riftdk1_fusion_h_ */
