/*
  A port of the sensor fusion of OpenHMD, src/fusion.c and the parts of
  src/omath.c it uses, at commit 85075b0. See SDL_hidapi_riftdk1_fusion.h.

  Copyright 2013, Fredrik Hultin.
  Copyright 2013, Jakob Bornecrantz.
  SPDX-License-Identifier: BSL-1.0

  Boost Software License - Version 1.0 - August 17th, 2003

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

#include "SDL_hidapi_riftdk1_fusion.h"

#include <math.h>
#include <string.h>

static float Fusion_Length3(const float v[3])
{
    return sqrtf(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
}

static void Fusion_Normalize3(float v[3])
{
    float len;

    if (v[0] == 0 && v[1] == 0 && v[2] == 0) {
        return;
    }
    len = Fusion_Length3(v);
    v[0] /= len;
    v[1] /= len;
    v[2] /= len;
}

static float Fusion_Angle3(const float a[3], const float b[3])
{
    const float dot = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
    const float lengths = Fusion_Length3(a) * Fusion_Length3(b);

    if (lengths == 0) {
        return 0;
    }
    return acosf(dot / lengths);
}

static void Fusion_QuatFromAxis(float q[4], const float axis[3], float angle)
{
    float norm[3];

    norm[0] = axis[0];
    norm[1] = axis[1];
    norm[2] = axis[2];
    Fusion_Normalize3(norm);
    q[0] = norm[0] * sinf(angle / 2.0f);
    q[1] = norm[1] * sinf(angle / 2.0f);
    q[2] = norm[2] * sinf(angle / 2.0f);
    q[3] = cosf(angle / 2.0f);
}

static void Fusion_QuatRotate(const float me[4], const float vec[3], float out[3])
{
    float q[4];

    q[0] = vec[0] * me[3] + vec[2] * me[1] - vec[1] * me[2];
    q[1] = vec[1] * me[3] + vec[0] * me[2] - vec[2] * me[0];
    q[2] = vec[2] * me[3] + vec[1] * me[0] - vec[0] * me[1];
    q[3] = vec[0] * me[0] + vec[1] * me[1] + vec[2] * me[2];

    out[0] = me[3] * q[0] + me[0] * q[3] + me[1] * q[2] - me[2] * q[1];
    out[1] = me[3] * q[1] + me[1] * q[3] + me[2] * q[0] - me[0] * q[2];
    out[2] = me[3] * q[2] + me[2] * q[3] + me[0] * q[1] - me[1] * q[0];
}

static void Fusion_QuatMult(const float me[4], const float q[4], float out[4])
{
    float result[4];

    result[0] = me[3] * q[0] + me[0] * q[3] + me[1] * q[2] - me[2] * q[1];
    result[1] = me[3] * q[1] - me[0] * q[2] + me[1] * q[3] + me[2] * q[0];
    result[2] = me[3] * q[2] + me[0] * q[1] - me[1] * q[0] + me[2] * q[3];
    result[3] = me[3] * q[3] - me[0] * q[0] - me[1] * q[1] - me[2] * q[2];
    memcpy(out, result, sizeof(result));
}

static void Fusion_QuatNormalize(float q[4])
{
    const float len = sqrtf(q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]);

    q[0] /= len;
    q[1] /= len;
    q[2] /= len;
    q[3] /= len;
}

void SDL_RiftDK1_FusionInit(SDL_RiftDK1Fusion *fusion)
{
    memset(fusion, 0, sizeof(*fusion));
    fusion->orient[3] = 1.0f;
    fusion->grav_gain = 0.05f;
    fusion->use_gravity = 1;
}

void SDL_RiftDK1_FusionUpdate(SDL_RiftDK1Fusion *fusion, float dt, const float ang_vel[3], const float accel[3])
{
    float world_accel[3];
    float ang_vel_length;

    Fusion_QuatRotate(fusion->orient, accel, world_accel);

    fusion->iterations += 1;
    fusion->time += dt;

    memcpy(fusion->accel_queue[fusion->accel_at], world_accel, sizeof(world_accel));
    fusion->accel_at = (fusion->accel_at + 1) % SDL_RIFTDK1_FUSION_QUEUE;

    ang_vel_length = Fusion_Length3(ang_vel);

    if (ang_vel_length > 0.0001f) {
        float rot_axis[3], delta_orient[4];

        rot_axis[0] = ang_vel[0] / ang_vel_length;
        rot_axis[1] = ang_vel[1] / ang_vel_length;
        rot_axis[2] = ang_vel[2] / ang_vel_length;
        Fusion_QuatFromAxis(delta_orient, rot_axis, ang_vel_length * dt);
        Fusion_QuatMult(fusion->orient, delta_orient, fusion->orient);
    }

    /* Gravity correction */
    if (fusion->use_gravity) {
        const float gravity_tolerance = .4f, ang_vel_tolerance = .1f;
        const float min_tilt_error = 0.05f, max_tilt_error = 0.01f;

        /* Count the samples the device holds level, and start over when it moves */
        fusion->device_level_count =
            (fabsf(Fusion_Length3(accel) - 9.82f) < gravity_tolerance * 2.0f && ang_vel_length < ang_vel_tolerance)
                ? fusion->device_level_count + 1 : 0;

        /* Level for long enough: correct from the mean of the queue */
        if (fusion->device_level_count > 50) {
            float accel_mean[3] = { 0, 0, 0 };
            int i;

            fusion->device_level_count = 0;
            for (i = 0; i < SDL_RIFTDK1_FUSION_QUEUE; ++i) {
                accel_mean[0] += fusion->accel_queue[i][0];
                accel_mean[1] += fusion->accel_queue[i][1];
                accel_mean[2] += fusion->accel_queue[i][2];
            }
            accel_mean[0] /= (float)SDL_RIFTDK1_FUSION_QUEUE;
            accel_mean[1] /= (float)SDL_RIFTDK1_FUSION_QUEUE;
            accel_mean[2] /= (float)SDL_RIFTDK1_FUSION_QUEUE;
            if (Fusion_Length3(accel_mean) - 9.82f < gravity_tolerance) {
                /* The cross product of what the device takes as up and
                   what gravity gives as down, reduced to its known terms */
                float tilt[3];
                float up[3] = { 0, 1.0f, 0 };
                float tilt_angle;

                tilt[0] = accel_mean[2];
                tilt[1] = 0;
                tilt[2] = -accel_mean[0];
                Fusion_Normalize3(tilt);
                Fusion_Normalize3(accel_mean);

                tilt_angle = Fusion_Angle3(up, accel_mean);
                if (tilt_angle > max_tilt_error) {
                    fusion->grav_error_angle = tilt_angle;
                    memcpy(fusion->grav_error_axis, tilt, sizeof(tilt));
                }
            }
        }

        /* Tilt correction */
        if (fusion->grav_error_angle > min_tilt_error) {
            float use_angle, corr_quat[4], old_orient[4];

            /* For the first 2000 samples the up axis snaps to the correction */
            if (fusion->iterations < 2000) {
                use_angle = -fusion->grav_error_angle;
                fusion->grav_error_angle = 0;
            } else {
                use_angle = -fusion->grav_gain * fusion->grav_error_angle * 0.005f * (5.0f * ang_vel_length + 1.0f);
                fusion->grav_error_angle += use_angle;
            }

            Fusion_QuatFromAxis(corr_quat, fusion->grav_error_axis, use_angle);
            memcpy(old_orient, fusion->orient, sizeof(old_orient));
            Fusion_QuatMult(corr_quat, old_orient, fusion->orient);
        }
    }

    /* Against drift from floating point quaternion products */
    Fusion_QuatNormalize(fusion->orient);
}
